version: '3'
networks:
  default:
    driver: bridge
volumes:
  libpostaldata:
    driver: local
services:
  libpostal:
    image: pelias/go-whosonfirst-libpostal
    container_name: pelias_libpostal
    restart: always
    ports: [ "8080:8080" ]
  schema:
    image: pelias/schema:master
    container_name: pelias_schema
    volumes:
      - "./pelias.json:/code/pelias.json"
  api:
    image: pelias/api:master
    container_name: pelias_api
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "4000:4000" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "libpostaldata:/usr/share/libpostal"
  geosearchapi:
    build:
      context: "https://github.com/nycplanning/labs-geosearch-api.git"
      # context: ../labs-geosearch-api # for local development
    container_name: geosearch_api
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "4300:4300" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
  placeholder:
    image: pelias/placeholder:master
    container_name: pelias_placeholder
    restart: always
    environment: [ "PORT=4100" ]
    ports: [ "4100:4100" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: pelias_whosonfirst
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  nycpad:
    build:
      context: "https://github.com/nycplanning/labs-geosearch-pad-importer.git"
      # context: ../labs-geosearch-pad-importer # for local development
    container_name: pelias_nycpad
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  pip-service:
    image: pelias/pip-service:master
    container_name: pelias_pip-service
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "4200:4200" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  elasticsearch:
    image: pelias/elasticsearch
    container_name: pelias_elasticsearch
    restart: always
    ports: [ "9200:9200", "9300:9300" ]
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
  tests:
    image: node:8-alpine
    container_name: pelias_acceptancetests
    build:
      context: "https://github.com/NYCPlanning/labs-geosearch-acceptance-tests.git"
      # context: ../labs-geosearch-acceptance-tests // for local development
    volumes:
      - "${DATA_DIR}/tests:/usr/share/tests/data"
    environment:
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
